/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aglenis' at '12/19/16 5:24 PM' with Gradle 2.11
 *
 * @author aglenis, @date 12/19/16 5:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
